### PR TITLE
Register Buildbuddy

### PR DESCRIPTION
**Pull request by thundergolfer**
### Description 

⚠️ Currently getting a blank white screen when hitting a build invocation page, eg. https://app.buildbuddy.io/invocation/93a9d34a-3dce-47f5-9770-59799ad9e65f

```
TypeError: Cannot read property 'buildEvent' of undefined
```

---

**Update:** The error appears to have gone now. I can see the BuildBuddy page

image

### CODE REVIEW

**Comment by thundergolfer** [comment]
cc @siggisim

**Comment by thundergolfer** [comment]
Had to revoke my Github Oauth tokens are having them in my environment and publishing them in a buildbuddy invocation URL 😖.

Might want to turn on `--strict_env`, and think twice before linking a Buildbuddy invocation URL publicly.

**Comment by siggisim** [comment]
Hey Jonathan - sorry about this. We're working on dropping environment variables for unauthenticated requests.

Will keep you posted when that's live.

**Comment by thundergolfer** [comment]
No worries, it was my mistake! 

That feature sounds good though.

**Pull request merged**
